name: Deploy

on:
  push:
    branches:
      - master

jobs:
#  build-and-deploy-frontend:
#    runs-on: ubuntu-latest
#    if: "!contains(github.event.head_commit.message, '[skip ci]')"
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
#
#      - name: Build and push frontend image
#        uses: docker/build-push-action@v5
#        with:
#          context: ./app/frontend
#          push: true
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bd_labs_frontend:latest
#
#    # Игнорируем изменения в файлах, которые не затрагивают код
#    paths-ignore:
#      - 'README.md'
#      - '**/*.md'
#
#  build-and-deploy-backend:
#    runs-on: ubuntu-latest
#    if: "!contains(github.event.head_commit.message, '[skip ci]')"
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
#
#      - name: Build and push backend image
#        uses: docker/build-push-action@v5
#        with:
#          context: ./app/backend
#          push: true
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bd_labs_backend:latest
#
#    paths-ignore:
#      - 'README.md'
#      - '**/*.md'
#
#  deploy:
#    runs-on: ubuntu-latest
#    needs: [build-and-deploy-frontend, build-and-deploy-backend]
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Deploy to server
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.SERVER_HOST }}
#          username: ${{ secrets.SERVER_USER }}
#          password: ${{ secrets.SERVER_PASSWORD }}
#          port: ${{ secrets.SERVER_PORT }}
#          script: |
#            cd bd_labs
#            docker-compose down
#            docker-compose pull
#            docker-compose up -d --force-recreate

  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Deploy to server
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            password: ${{ secrets.SERVER_PASSWORD }}
            port: ${{ secrets.SERVER_PORT }}
            script: |
              cd bd_labs
              cd BD_GVOZDKOV
              git pull
              docker-compose up -d --force-recreate
